@startuml
  class CurriculumVitae {
    + persona: Persona
    + hitos: Hito[]
    + habilidades: Habilidad[]
    + intereses: Interes[]
  }

  class Interes {
    tema: string
  }

  class Priorizable {
    nombre: string
    prioridad: integer
  }

  class Habilidad {
    + nombre: string
    + expertis: Expertis
    + categoria: Priorizable
  }

  class Periodo {
    + inicio: Date
    + termino: Date
  }

  class Hito {
    + fecha: Periodo | Date
    + testigo: Persona | Organizacion
    + acontecimiento: string
    + evidencia: Evidencia
    + categoria: Priorizable
  }

  class URL {
    query_string: string
  }

  class Evidencia {
    + vinculo : URL
    + data: Bloob
  }

  class Organizacion extends Contactable {
    razon_social: string
  }

  enum Expertis {
      BASICO
      INTERMEDIO
      AVANZADO
      EXPERTO
  }

  enum Rol {
      USUARIO
      ADMINISTRADOR
      DESARROLLADOR
  }

  class Persona extends Contactable {
    + nombre: string
    + apellido_paterno: string
    + apellido_materno: string
  }

  class Contactable {
    + contacto: Contacto[]
  }

  interface Contacto {
      + medio: Medio
      + valor: string
  }

  interface Date {
    timestamp: integer
    Date(date: string)
    toString()
  }

  enum Medio {
    GPS
    SERVICIO_POSTAL
    CORREO_ELECTRONICO
    TELEFONO
    HIPERTEXTO
  }

  Contacto <-- Medio

  CurriculumVitae <-- Persona
  CurriculumVitae <-- Habilidad
  CurriculumVitae <-- Hito
  CurriculumVitae <-- Interes

  Evidencia <-- URL

  Habilidad <-- Expertis
  Habilidad <-- Priorizable
  Habilidad <-- Rol

  Hito <-- Priorizable
  Hito <-- Evidencia
  Hito <-- Persona
  Hito <-- Organizacion
  Hito <-- Date
  Hito <-- Periodo

  Contactable <-- Contacto

  Periodo <-- Date
@enduml
